name: Pull Request CI

on:
  pull_request:
    branches: [main]

jobs:
  changeset-check:
    runs-on: ubuntu-latest
    name: Changeset Status Check
    if: github.ref != 'refs/heads/changeset-release/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: yarn install --immutable
      - run: yarn changeset status --since=origin/main
  changeset-check-skipped:
    runs-on: ubuntu-latest
    name: Changeset Status Check
    if: github.ref == 'refs/heads/changeset-release/main'
    steps:
      - run: 'echo "No check required"'
