name: Release

on:
  push:
  # workflow_run:
  #  workflows: ['Testing CI']
  #  branches: [main]
  #  types:
  #    - completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name:
      Release packages
      # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      published: 'true' # ${{ steps.changesets.outputs.published }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Install Dependencies
      #  run: yarn install --immutable
      # - name: Create Release Pull Request or Publish to npm
      #  id: changesets
      #  uses: changesets/action@v1
      #  with:
      #    title: Upcoming release
      #    commit: Upcoming release changes
      #    publish: yarn release
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  verify-packages:
    needs: [release]
    name: Verify published packages
    if: needs.release.outputs.published == 'true'
    uses: ./.github/workflows/verify-packages-workflow.yml
    with:
      prepare_mode: npm
